author: [James Lemin]
institute: [an institute]
title: [this is the main title]
tags:
  - tags
  - are
  - nice
  - yeah
pdf-title: [this will also be the filename]
author-meta: [James Lemin]
draft: false
date: [2020]
titlepage: true
toc-own-page: true
toc-title: [Contents]
toc-depth: [2]
lot: True #remove line to not include List of tables
lof: True #remove line to not include List of figures
bibliography: [references.bib]
biblio-title: [References]
